version: '2'
services:
  postgres_host:
    image: postgres:10-alpine
    restart: always
    ports: ["5435:5432"]
  data-client:
    build:
      context: .
    depends_on:
      - postgres_host
    tty: true
    environment:
      - APP_POSTGRES_HOST=postgres_host
      - APP_POSTGRES_PORT=5432
    volumes:
      - /home/data/hello_sql_world:/data
    links: [postgres_host]
